---
- hosts: web-server
  remote_user: ec2-user 
  become: yes
  gather_facts: no
  tasks:
  - name: Install httpd
    yum:
      name: httpd
      state: present
  - name: To start the services
    service: 
      name: httpd
      state: started
      enabled: yes
