---
- name: To create an ec2 instance for web servers
  hosts: localhost
  connection: local
  tasks:
  - name: To create a instances
    ec2:
      key_name: jumb-box-key-pair
      instance_type: t2.micro
      region: ap-southeast-1
      image: ami-05c64f7b4062b0a21
 #     security_group: jump-box-sg
      wait: yes
      group: default 
      count: 1
      vpc_subnet_id: subnet-037da61d6ebd4dfdd
      instance_tags:
        Name: DB01
    register: ec2
