---
- name: Add a Prometheus user
  user:
    name: prometheus
    comment: "Add a Prometheus user"
    create_home: no
    shell: /bin/false

- name: Create directories.
  file: path="{{item}}" state=directory mode=0755 owner=prometheus group=prometheus
  with_items:
    - /etc/prometheus
    - /var/lib/prometheus

- name: download prometheus binary
  get_url:
    url: https://github.com/prometheus/prometheus/releases/download/v2.15.2/prometheus-2.15.2.linux-amd64.tar.gz
    dest: /var/tmp/

- name: Extract prometheus package
  unarchive:
    src: /var/tmp/prometheus-2.15.2.linux-amd64.tar.gz
    dest: /var/tmp/
    remote_src: yes

- name: Copy prometheus
  copy:
    src: /var/tmp/prometheus-2.15.2.linux-amd64/prometheus
    dest: /usr/local/bin/
    mode: 0755
    owner: prometheus
    group: prometheus

- name: Copy promtool
  copy:
    src: /var/tmp/prometheus-2.15.2.linux-amd64/promtool
    dest: /usr/local/bin/
    mode: 0755
    owner: prometheus
    group: prometheus

- name: Copy consoles
  copy:
    src: /var/tmp/prometheus-2.15.2.linux-amd64/consoles
    dest: /etc/prometheus
    owner: prometheus
    group: prometheus

- name: Copy console_libraries
  copy:
    src: /var/tmp/prometheus-2.15.2.linux-amd64/console_libraries
    dest: /etc/prometheus
    owner: prometheus
    group: prometheus

- name: touch the file
  file:
    path: /etc/prometheus/prometheus.yml
    state: touch
    owner: prometheus
    group: prometheus

- name: modify Prometheus configuration file
  blockinfile:
    dest: /etc/prometheus/prometheus.yml
    block: |
      global:
        scrape_interval: 10s
      scrape_configs:
        - job_name: 'prometheus_master'
          scrape_interval: 5s
          static_configs:
            - targets: ['localhost:9090']

- name: touch the file
  file: path=/etc/systemd/system/prometheus.service state=touch owner=prometheus group=prometheus

- name: modify Prometheus configuration file
  blockinfile:
    dest: /etc/systemd/system/prometheus.service
    block: |
      [Unit]
      Description=Prometheus
      Wants=network-online.target
      After=network-online.target

      [Service]
      User=prometheus
      Group=prometheus
      Type=simple
      ExecStart=/usr/local/bin/prometheus \
      --config.file /etc/prometheus/prometheus.yml \
      --storage.tsdb.path /var/lib/prometheus/ \
      --web.console.templates=/etc/prometheus/consoles \
      --web.console.libraries=/etc/prometheus/console_libraries
      [Install]
      WantedBy=multi-user.target

- name: reload service
  service:
    name: prometheus
    state: started
